<a href="https://colab.research.google.com/github/furkanoruc/short-text-distances-ranking-bert/blob/main/project_text_distance_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sorting Distances Between Jobs via BERT Language Model, TF-IDF, Cosine Distance and Levenshtein Distance

In [ ]:
import numpy as np 
import seaborn as sns
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os
import sys
import glob
from math import radians, cos, sin, asin, sqrt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import textdistance

In [ ]:
pip install textdistance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
df = pd.read_excel("english_list.xlsx")
df.drop(columns="Unnamed: 3", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14051 entries, 0 to 14050
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   ServiceId      14051 non-null  int64 
 1   TRServiceName  14035 non-null  object
 2   ENServiceName  14051 non-null  object
dtypes: int64(1), object(2)
memory usage: 329.4+ KB


## 1. Bert

In [ ]:
pip install sentence-transformers

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')
#Encoding:
sen_embeddings = model.encode(df["ENServiceName"])
sen_embeddings.shape

In [ ]:
from scipy import sparse
#df_sparse = sparse.csr_matrix(df_dense_list)
similarities = cosine_similarity(sen_embeddings)

In [ ]:
id_similarity = np.argsort(similarities[9819])[-50:]

In [ ]:
df[9819:9820]

ServiceId TRServiceName ENServiceName
9819      54204      Marangoz     Carpenter

In [ ]:
df.iloc[id_similarity]

ServiceId           TRServiceName                      ENServiceName
5622       50000               Bina Şefi                     Building Chief
9955       54340  Mekanik Şef Yardımcısı         Mechanical Assistant Chief
12643      57036             Teknik İşçi                   Technical Worker
788         1153           Teknik Ressam                          Draftsman
9949       54334       Mekanik Personeli               Mechanical Personnel
8604       52987         Kalıp Operatörü                      Mold Operator
9923       54308     Mekanik Atölye Şefi          Mechanical Workshop Chief
5269       49647         Bakım Teknikeri             Maintenance Technician
5270       49648        Bakım Teknisyeni             Maintenance Technician
4191        8222      Makine Süpervizörü              Mechanical Supervisor
8374       52757  İş Makinesi Teknisyeni  Construction equipment technician
9924       54309   Mekanik Atölye Ustası         Mechanical Workshop Master
4175        8200      Mekanik İşler Şefi             Mechanical Works Chief
5169       49547        Atölye Mühendisi                  Workshop engineer
8617       53000            Kalıp Uzmanı                    Mold Specialist
26            86           Atölye İşçisi                Mechanical Repairer
4979       49357      Apartman Görevlisi                 Building Caretaker
5268       49646              Bakım Şefi                  Maintenance chief
4227        8262             Alet İşçisi                  Instrument Worker
9800       54185      Malzeme Teknisyeni                Material technician
4538        9299          Mekanik Ustası                  Mechanical Master
4138        4982            Liman İşçisi                             Docker
791         1156             Konstrüktör                        Constructor
4520        9236          Alet Operatörü                      Tool Operator
4165        5012            Beden Işçisi                      Manual Worker
4418        8947        İnşaat Mühendisi              Construction Engineer
9962       54347      Mekanik Teknisyeni              Mechanical Technician
12453      56846            Tamir Ustası                          Repairman
4540        9309                Ustabaşı                            Foreman
7269       51649                  Formen                            foreman
4284        8406             Mekanik Şef                   Mechanical Chief
8264       52647             İnşaat Şefi                 Construction chief
8616       52999         Kalıp Teknikeri                    Mold Technician
802         1168    Kalıpçılık Teknikeri                    Mold Technician
833         1201        Kalıp Teknisyeni                    Mold Technician
2090        2672                 Nalbant                         Blacksmith
8371       52754      Iş Makineleri Şefi       Construction equipment chief
4587        9711                    Işçi                             Worker
30           131               Müteahhit                         Contractor
595          937         Yapı Teknisyeni                Building Technician
4321        8551            Kalıp Ustası                        Mold Master
51           167           İnşaat Ustası                Construction Master
4             31        İnşaat Teknikeri            Construction Technician
8266       52649       Inşaat Teknisyeni            Construction technician
4236        8271                Kaynakçı                             Welder
4521        9244        İnşaat Demircisi            Construction Blacksmith
6686       51065     El Sanatları Ustası                          Craftsman
56           172        İnşaat Marangozu               Carpenter And Joiner
1833        2391        Atölye Marangozu                 Workshop Carpenter
9819       54204                Marangoz                          Carpenter

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-mpnet-base-v2')
#Encoding:
sen_embeddings_2 = model.encode(df["ENServiceName"])
sen_embeddings_2.shape

In [ ]:
similarities_2 = cosine_similarity(sen_embeddings)

In [ ]:
id_similarity_2 = np.argsort(similarities_2[8264])[-20:]

In [ ]:
df[8264:8265]

ServiceId TRServiceName       ENServiceName
8264      52647   İnşaat Şefi  Construction chief

In [ ]:
df.iloc[id_similarity_2]

ServiceId           TRServiceName                 ENServiceName
5268       49646              Bakım Şefi             Maintenance chief
49           165          Inşaat Bekçisi            Construction Guard
11052      55439             Proje Amiri                 Project chief
12350      56743      Şantiye Teknisyeni  Construction site technician
8260       52643        İnşaat Personeli            Construction staff
12348      56741       Şantiye Mühendisi    Construction site engineer
12349      56742       Şantiye Sorumlusu  Construction site supervisor
8266       52649       Inşaat Teknisyeni       Construction technician
4             31        İnşaat Teknikeri       Construction Technician
8263       52646      İnşaat Süpervizörü       Construction supervisor
4418        8947        İnşaat Mühendisi         Construction Engineer
8261       52644     İnşaat Proje Müdürü  Construction Project Manager
8262       52645  İnşaat Proje Sorumlusu  Construction Project Manager
4178        8204           İnşaat Müdürü          Construction Manager
5622       50000               Bina Şefi                Building Chief
51           167           İnşaat Ustası           Construction Master
31           132        Inşaat Direktörü         Construction Director
13623      58016      Yapım Kontrol Şefi    Construction control chief
8371       52754      Iş Makineleri Şefi  Construction equipment chief
8264       52647             İnşaat Şefi            Construction chief

## 2. TF-IDF

In [ ]:
df

In [ ]:
vectorizer = TfidfVectorizer(stop_words= "english")
vectors = vectorizer.fit_transform(df["ENServiceName"])
feature_names = vectorizer.get_feature_names_out()
dense = vectors.todense()
denselist = dense.tolist()
df_dense_list = pd.DataFrame(denselist, columns=feature_names)

In [ ]:
df_dense_list.head(10)

31   3d  3ds  5000  9001  abap  able  abrasive  abroad  absorbent  ...  \
0  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
1  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
2  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
3  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
4  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
5  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
6  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
7  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
8  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   
9  0.0  0.0  0.0   0.0   0.0   0.0   0.0       0.0     0.0        0.0  ...   

   zoology  zoopathologist  zootechnist  zumba  çerçi  çeviri  şile  şirenz  \
0      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
1      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
2      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
3      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
4      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
5      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
6      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
7      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
8      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   
9      0.0             0.0          0.0    0.0    0.0     0.0   0.0     0.0   

   şoför  хозяин  
0    0.0     0.0  
1    0.0     0.0  
2    0.0     0.0  
3    0.0     0.0  
4    0.0     0.0  
5    0.0     0.0  
6    0.0     0.0  
7    0.0     0.0  
8    0.0     0.0  
9    0.0     0.0  

[10 rows x 4869 columns]

In [ ]:
np.where(cosine_similarity(df_dense_list[1:2],df_dense_list[2:len(df_dense_list)-1]) == min(cosine_similarity(df_dense_list[1:2],df_dense_list[2:len(df_dense_list)-1])))


(array([0, 0, 0, ..., 0, 0, 0]),
 array([    0,     1,     2, ..., 14045, 14046, 14047]))

In [ ]:
dense

4869

In [ ]:
#matrix = pd.DataFrame(cosine_similarity(denselist, denselist), index=denselist, columns=feature_names)

In [ ]:
lst = []
for index, row in df_dense_list.iterrows():
  lst.append(cosine_similarity(df_dense_list[1:2], df_dense_list[2:len(df_dense_list)]))

In [ ]:
from scipy import sparse
df_sparse = sparse.csr_matrix(df_dense_list)
similarities = cosine_similarity(df_sparse)

In [ ]:
sim = np.array(similarities)
sim.shape

(14051, 14051)

In [ ]:
np.argsort(sim[15])[-10:]

array([3376,  768, 6551, 8547,    6, 8549, 8548,   17,   29,   15])

In [ ]:
id_similarity = np.argsort(sim[7268])[-20:]

In [ ]:
df[7268:7269]

ServiceId       TRServiceName      ENServiceName
7268      51648  Forklift Operatörü  Forklift operator

In [ ]:
df.iloc[id_similarity]

ServiceId                        TRServiceName  \
11852      56243                     Servis Operatörü   
11846      56237                   Servis İşletmecisi   
12018      56409               Sistem Uzman Operatörü   
12660      57053                      Teknik Operator   
8679       53062                     Kalite Operatörü   
12515      56908                    Tasarım Operatörü   
11087      55474                      Proje Operatörü   
9042       53425                     Kıdemli Operatör   
8177       52559                     İmalat Operatörü   
5261       49639                      Bakım Operatörü   
10737      55124              Parça Kontrol Operatörü   
13306      57699                     Üretim Operatörü   
9687       54072                     Makine Operatörü   
10496      54882                  Operatör Yardımcısı   
1277        1749                     Sistem İşletmeni   
5061       49439                       AR-GE Operatör   
12012      56403                     Sistem Operatörü   
3998        4822  Yan Forklift (Reachtruck) Operatörü   
7267       51647             Forklift Bakım Teknikeri   
7268       51648                   Forklift Operatörü   

                              ENServiceName  
11852                      Service Operator  
11846                      Service Operator  
12018                System Expert Operator  
12660                    Technical Operator  
8679                       Quality Operator  
12515                       Design Operator  
11087                      Project operator  
9042                        Senior operator  
8177                 Manufacturing Operator  
5261                   Maintenance operator  
10737                 Part Control Operator  
13306                   Production Operator  
9687                       Machine operator  
10496                    Assistant Operator  
1277                        System Operator  
5061                           R&D Operator  
12012                       System Operator  
3998    Side Forklift (Reachtruck) Operator  
7267        Forklift Maintenance Technician  
7268                      Forklift operator

In [ ]:
df[12650:12651]

ServiceId TRServiceName      ENServiceName
12650      57043  Teknik Müdür  Technical manager

In [ ]:
lev = textdistance.levenshtein.distance(["Technical managerXXXXY", "Z "], ["ZZ"])
#df.loc[:,"ENServiceName"],df.loc[:,"ENServiceName"]

In [ ]:
lev[2]

In [ ]:
lst = [1,2,3]
max(lst)

3

In [ ]:
max([1,2,3,4])

4